[[announcement]]
title = "Announcing Chitchai 0.1"
date = "2023-11-05"
author = "Feng Liang"
content = """ We are pleased to announce the release of Chitchai 聊斋 0.1. This is the first release of Chitchai.
Chitchai is a chat room for chatting with **multiple** agents. It's like group chats of [character.ai](https://character.ai), but without subscription. You need subscriptions from GPT providers, though, OpenAI and Azure OpenAI supported for now.

Features:
1. Chat with multiple agents. Demo on chitchai.dev where you can chat with 2 default agents, a designer and a programmer.
2. Customize your own agents. As for now, by building Chitchai from source code, you can customize your own agents. We will provide a web interface for this in 0.2.
3. Chitchai is completely local. We don't need your data. Your chat will only be sent to GPT providers you trust.
4. Chitchai is open and free for all forever.

Dev features:
1. Chitchai is built with Rust and Dioxus. Almost Rust except CSS.
2. Chitchai is wasm-based. It can be run in browser, desktop and mobile.
3. You can use it as a crate of a collection of chat components. For now you have to get it from git repo, but we will publish it to crates.io soon (when wasm support is upstreamed to `async-openai`).

> How does it work?
>
> Compared to AutoGen, Chitchai is super simple thanks to the intelligence of GPT-4.
> Each agent in a chat room internally has its own chat history, in which only the initial system prompt is different.
> Messages in agent histories are denoted with agent/user names, and then magically GPT-4 correctly knows who is who and who says what (just like us humans).
> This ability is remarkable but we humans take it for granted. However, GPT-3.5 or any LLMs like it does not have this ability (yet?).

> A bit of research?
>
> Can we do AutoGen just by using aformentioned ability of GPT-4? That's a good question. I don't know. But I think it's worth a try.


Please check the [Chitchai repo](https://github.com/ifsheldon/chitchai) for more details! And we always welcome your feedbacks as issues and PRs.
"""