[[announcement]]
title = "Announcing Chitchai 0.1"
date = "2023-11-05"
author = "Feng Liang"
content = """ We are pleased to announce the release of Chitchai 聊斋 0.1. This is the first release of Chitchai.
Chitchai is a chat room for chatting with MULTIPLE agents. It's like group chats of character.ai, but without subscription. You need subscriptions from GPT providers, though, OpenAI and Azure OpenAI supported for now.

Features:
1. Chat with multiple agents. Demo on chitchai.dev where you can chat with 2 default agents, a designer and a programmer.
2. Customize your own agents. As for now, by building Chitchai from source code, you can customize your own agents. We will provide a web interface for this in 0.2.
3. Chitchai is completely local. We don't need your data. Your chat will only be sent to GPT providers you trust.
4. Chitchai is open and free for all forever.

Dev features:
1. Chitchai is built with Rust and Dioxus. Almost Rust except CSS.
2. Chitchai is wasm-based. It can be run in browser, desktop and mobile.

Please check the [github.com/ifsheldon/chitchai](github.com/ifsheldon/chitchai) for more details! And we always welcome your feedbacks as issues and PRs.
"""